from . import res_config_settings
from . import product_pricelist
from . import customer_deposit
from . import account_move
from . import sale_order
from . import account_journal
from . import account_payment
from . import account_invoice
from . import res_partner